---

- name: Determine the running kernel release
  command: uname -r
  register: kernel_release

# - name: Add the WireGuard PPA
#   apt_repository:
#       repo: 'deb http://deb.debian.org/debian/ unstable main'
#   register: wireguard_add_apt_repository
#   until: not wireguard_add_apt_repository.failed
#   retries: "{{ apt_repository_retries }}"
#   delay: "{{ apt_repository_delay }}"

- name: Install the WireGuard packages
  apt:
    name: "{{ item }}"
  with_items:
    - wireguard
